### PR TITLE
Update CorbTask to 2.3.0 and ability to dynamically enhance CorbTask with CoRB Options

### PR DESCRIPTION
**Pull request by hansenmc**
- Updated CoRB references to 2.3.0
- Changed the CorbTask to attempt to obtain the list of CoRB options from the Options class. If not available, uses default list of options.
- Bumped the bintray plugin version to 1.6

### CODE REVIEW

**Comment by rjrudin** [comment]
@hansenmc I'll merge this in soon, working on some other features in the dependent libraries so I can get 2.2.0 ready.

**Comment by rjrudin** [comment]
Ack - I completely forgot about this for 2.2.0-RC1. 

I'm going to kick the tires on 2.2.0-RC1 today for two of my projects. I'll ensure this is 2.2.0 final, as well as 2.2.0-RC2 if there is one.

**Comment by rjrudin** [comment]
@hansenmc This is now on master and dev. Do you want a separate 2.2.0-RC2 to try it out, or do you want it build it and try it locally, or are you confident enough in it that I can just include it in the final 2.2.0?

**Comment by hansenmc** [comment]
It should be good to go, but is always best to test. I'll pull and build locally tonight.

**Comment by hansenmc** [comment]
Building locally and running worked just fine. It should be good to go. FYI - We will be releasing CORB v3.3.1 soon. With this release of ml-gradle it will be less important to keep up, users should be able to adjust their dependencies and the CorbTask will support any newly added options auto-magically via reflection and groovy MetaClass enhancements at runtime.

**Pull request merged**
